{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spiralize
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spiralize_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spiralize/spiralize_{{ version }}.tar.gz
  sha256: 4833d9d1a26c0a4d113d1f2d4dcb7820dcc2212101b3fb19b815513256020854

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-getoptlong >=0.1.8
    - r-globaloptions >=0.1.1
    - r-circlize
    - r-lubridate
  run:
    - r-base
    - r-getoptlong >=0.1.8
    - r-globaloptions >=0.1.1
    - r-circlize
    - r-lubridate

test:
  commands:
    - $R -e "library('spiralize')"           # [not win]
    - "\"%R%\" -e \"library('spiralize')\""  # [win]

about:
  home: https://github.com/jokergoo/spiralize
  license: MIT
  summary: 'It visualizes data along an Archimedean spiral <https://en.wikipedia.org/wiki/Archimedean_spiral>. It has two major advantages for visualization: 1. It is able to visualize data with very long axis with high resolution. 2. It is efficient for time series data to reveal periodic patterns.'
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
